services:
  jupyter:
    image: continuumio/miniconda3
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/opt/notebooks
      - conda_env:/opt/conda
    command: >
      /bin/bash -c "conda install -c conda-forge notebook jupyterlab -y &&
                    jupyter lab --notebook-dir=/opt/notebooks --ip='0.0.0.0' --port=8888 --no-browser --allow-root"

  code-server:
    image: lscr.io/linuxserver/code-server:latest
    container_name: code-server
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PASSWORD=password #optional
      - SUDO_PASSWORD=password #optional
      - DEFAULT_WORKSPACE=/config/workspace #optional
      - CUSTOM_ENV=PATH=/opt/conda/bin:$PATH
    volumes:
      - ./config:/config
      - conda_env:/opt/conda
      - ./:/config/workspace
    ports:
      - 8443:8443
    restart: unless-stopped

volumes:
  conda_env: